### ISSUE TITLE
Can not use on DNN 9.2.1

### ISSUE THREAD

**Issue by amy-casey** [DNNCommunity/DNN.Faq#50]
## Describe the bug
I am able to install either of the two most recent releases on my DNN 9.2.1 site, but when I add to page I get a general exception

## To Reproduce
Add module to any page on my 9.2.1 install 

## Error log
StackTrace: InnerMessage:Could not load file or assembly 'DotNetNuke.Web.Deprecated' or one of its dependencies. The system cannot find the file specified.

InnerStackTrace: at System.Web.UI.TemplateParser.ParseString(String text, VirtualPath virtualPath, Encoding fileEncoding) at System.Web.UI.TemplateParser.ParseFile(String physicalPath, VirtualPath virtualPath) at System.Web.UI.TemplateParser.ParseInternal() at System.Web.UI.TemplateParser.Parse() at System.Web.Compilation.BaseTemplateBuildProvider.get_CodeCompilerType() at System.Web.Compilation.BuildProvider.GetCompilerTypeFromBuildProvider(BuildProvider buildProvider) at System.Web.Compilation.BuildProvidersCompiler.ProcessBuildProviders() at System.Web.Compilation.BuildProvidersCompiler.PerformBuild() at System.Web.Compilation.BuildManager.CompileWebFile(VirtualPath virtualPath) at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate) at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate) at System.Web.UI.TemplateControl.LoadControl(VirtualPath virtualPath) at DotNetNuke.UI.ControlUtilities.LoadControl[T](TemplateControl containerControl, String ControlSrc) at DotNetNuke.UI.Modules.WebFormsModuleControlFactory.CreateModuleControl(TemplateControl containerControl, ModuleInfo moduleConfiguration) at DotNetNuke.UI.Modules.ModuleControlFactory.LoadModuleControl(TemplateControl containerControl, ModuleInfo moduleConfiguration) at DotNetNuke.UI.Modules.ModuleHost.LoadModuleControl()

## Additional context
Have no issues on my 9.0 site with this module

**Comment by valadas** [comment]
Can you check if you have the file DotNetNuke.Web.Deprecated.dll in the bin folder of your site, if not 

Best option is to upgrade to Dnn 9.2.2 which should fix that missing file + other issues, improvements, etc. The download location for that is at https://github.com/dnnsoftware/Dnn.Platform/releases

If and only if there is a major issue preventing you to upgrade to 9.2.2 (I doubt it, no breaking changes are expected there) then an alternative is to grad that missing dll from the 9.2.1 release at https://github.com/dnnsoftware/Dnn.Platform/releases/tag/v9.2.1 
In that zip, got to install -> modules

Then either you can install the DNNCE_01_Web-Deprecates_09.02.01_install.zip file on the site just like any other module or you can just grab the dll inside and place it in the bin folder of your site.

But to re-iterate, it is not normal that this file is missing and I would rather upgrade to 9.2.2 than fixing that issue since it is not normal that this file is missing, there might be other stuff that is not correct on this installation.

I will close this issue but feel free to comment if not resolved by these steps and I will gladly reopen.
